package Datos;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 01 01:38:59 CST 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int COMA = 2;
  public static final int error = 1;
  public static final int ALFANUMERICO = 4;
  public static final int PCOMA = 3;
  public static final int EOF = 0;
}

