/*
 * Etools.java
 *
 * Created on 11 de mayo de 2007, 09:33 PM
 */

package Escaleras;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JRootPane;
import javax.swing.JTextArea;

/**
 *
 * @author  ONIXX
 */
public class Etools extends javax.swing.JFrame {
    
    /** Creates new form Etools */
    public Etools() {
        initComponents();
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        Tpos = new javax.swing.JTextArea();
        Bregresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serpientes y Escaleras");
        setAlwaysOnTop(true);
        setResizable(false);
        setUndecorated(true);
        Tpos.setColumns(20);
        Tpos.setEditable(false);
        Tpos.setLineWrap(true);
        Tpos.setRows(5);
        Tpos.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Tpos);

        Bregresar.setText("Regresar");
        Bregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("POSICIONES DEL JUEGO ACTUAL");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(64, 64, 64))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 442, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(Bregresar)))
                        .add(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 366, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Bregresar)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Oculta la ventana*/
    private void BregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BregresarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etools().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bregresar;
    private javax.swing.JTextArea Tpos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**Hace los reportes en html*/
    void HacerReportes(String nombre,int lanzamientos,String fecha,String hora,String competidores) {
        try{
            File archivo = new File("c:/Escaleras/Historial.html"),datos = new File("c:/Escaleras/Hdatos");
            PrintWriter out = new PrintWriter(new FileWriter(archivo)), H = new PrintWriter(new FileWriter(datos,true));
            
            H.println("<tr align=center><td>"+nombre+"</td><td>"+lanzamientos+"</td><td>"+fecha+"</td><td>"+hora+"</td><td>"+competidores+"</td></tr>");
            H.close();
            
            BufferedReader in = new BufferedReader(new FileReader(datos));
            JTextArea Texto=new JTextArea();
            String text = "";            
            Texto.setText("");      
            while ((text = in.readLine()) != null){
                text = text + "\n";                
                Texto.append(text);
            }
            
            out.println("<html><head><title>Historial</title></head><body bgcolor=\"#97D7FD\"><h2 align=center>HISTORIAL</h2><p>&nbsp;<p><center><table border=1>"
            +"<tr align=center><td>NOMBRE</td><td>LANZAMIENTOS</td><td>FECHA</td><td>HORA</td><td>COMPETIDORES</td></tr>"+Texto.getText()+"</table></center></body></html>");
            out.close();
            
        }catch(Exception ex){}
    }

    /**Carga las posiciones de las casillas en el arhivo en uso*/
    void cargarPosiciones(JTextArea tmpCargar) {
        Tpos.setText(tmpCargar.getText());
    }

    
}
