/*
 * Menu.java
 *
 * Created on 30 de abril de 2007, 07:32 PM
 */

package juegos;

import Escaleras.Escaleras;
import Puzzle.Puzzle;
import Hanoi.Hanoi;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author  ONIXX
 */
public class Menu extends javax.swing.JFrame {
    Color normal = new Color(0,51,153);
    
    /** Crea un menú */
    public Menu() {
        initComponents();
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pu = new javax.swing.JLabel();
        sye = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        th = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        LacercaDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        setUndecorated(true);
        pu.setFont(new java.awt.Font("Tahoma", 0, 24));
        pu.setForeground(new java.awt.Color(0, 51, 153));
        pu.setText("Jugar Puzzle");
        pu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(210, 209, 209), new java.awt.Color(163, 162, 162)));
        pu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                puMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                puMouseExited(evt);
            }
        });

        sye.setFont(new java.awt.Font("Tahoma", 0, 24));
        sye.setForeground(new java.awt.Color(0, 51, 153));
        sye.setText("Jugar Serpientes y Escaleras");
        sye.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(210, 209, 209), new java.awt.Color(163, 162, 162)));
        sye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                syeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                syeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                syeMouseExited(evt);
            }
        });

        jLabel3.setText("Hecho por: GERARDO PINEDA");

        jLabel4.setText("2006-11226");

        th.setFont(new java.awt.Font("Tahoma", 0, 24));
        th.setForeground(new java.awt.Color(0, 51, 153));
        th.setText("Jugar Torres de Hanoi");
        th.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(210, 209, 209), new java.awt.Color(163, 162, 162)));
        th.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thMouseExited(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 0, 24));
        salir.setForeground(new java.awt.Color(0, 51, 153));
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(210, 209, 209), new java.awt.Color(163, 162, 162)));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        LacercaDe.setFont(new java.awt.Font("Tahoma", 0, 24));
        LacercaDe.setForeground(new java.awt.Color(0, 51, 153));
        LacercaDe.setText("Acerca de");
        LacercaDe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(210, 209, 209), new java.awt.Color(163, 162, 162)));
        LacercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LacercaDeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LacercaDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LacercaDeMouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, sye)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, th)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pu)))
            .add(layout.createSequentialGroup()
                .add(salir)
                .addContainerGap(461, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(LacercaDe)
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .add(th)
                .add(32, 32, 32)
                .add(pu)
                .add(34, 34, 34)
                .add(sye)
                .add(50, 50, 50)
                .add(LacercaDe)
                .add(17, 17, 17)
                .add(salir)
                .add(20, 20, 20)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Abre la ventana de serpientes y escaleras*/
    private void syeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_syeMouseClicked
        Escaleras nuevoE = new Escaleras();
        nuevoE.setVisible(true);
    }//GEN-LAST:event_syeMouseClicked

    /**Abre la ventana de torres de hanoi*/
    private void thMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thMouseClicked
        Hanoi nuevoH = new Hanoi();
        nuevoH.setVisible(true);
    }//GEN-LAST:event_thMouseClicked

    private void LacercaDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LacercaDeMouseExited
        LacercaDe.setForeground(normal);
    }//GEN-LAST:event_LacercaDeMouseExited

    private void LacercaDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LacercaDeMouseEntered
        LacercaDe.setForeground(Color.WHITE);
    }//GEN-LAST:event_LacercaDeMouseEntered

    /**Despliega un mensaje con los datos del creador*/
    private void LacercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LacercaDeMouseClicked
        JOptionPane.showMessageDialog(this,"Hecho por Gerardo Pineda\nCarnet: 2006-11226\nIPC1","Datos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LacercaDeMouseClicked

    /**Abre la ventana de puzzle*/
    private void puMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puMouseClicked
        Puzzle nuevoP = new Puzzle();
        nuevoP.setVisible(true);
    }//GEN-LAST:event_puMouseClicked

    private void syeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_syeMouseExited
        sye.setForeground(normal);
    }//GEN-LAST:event_syeMouseExited

    private void syeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_syeMouseEntered
        sye.setForeground(Color.WHITE);
    }//GEN-LAST:event_syeMouseEntered

    private void puMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puMouseExited
        pu.setForeground(normal);
    }//GEN-LAST:event_puMouseExited

    private void puMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puMouseEntered
        pu.setForeground(Color.WHITE);
    }//GEN-LAST:event_puMouseEntered

    private void thMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thMouseExited
        th.setForeground(normal);
    }//GEN-LAST:event_thMouseExited

    private void thMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thMouseEntered
        th.setForeground(Color.WHITE);
    }//GEN-LAST:event_thMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setForeground(normal);
    }//GEN-LAST:event_salirMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirMouseEntered

    /**Cierra el programa*/
    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        JOptionPane pane=new JOptionPane("Salir?",JOptionPane.QUESTION_MESSAGE,JOptionPane.YES_NO_OPTION);
        JDialog dialog=pane.createDialog(this,"Salida");
        dialog.setDefaultCloseOperation(dialog.DO_NOTHING_ON_CLOSE);
        dialog.setVisible(true);
        Object s=pane.getValue();
        if(((Integer)s).intValue()==pane.NO_OPTION)return;
        else System.exit(0);
    }//GEN-LAST:event_salirMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LacercaDe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel pu;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel sye;
    private javax.swing.JLabel th;
    // End of variables declaration//GEN-END:variables
    
}
