/*
 * InterfazGrafica.java
 *
 * Created on 30 de octubre de 2007, 04:14 PM
 */

package Proyecto2;

import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;


/**
 * Interfaz grafica del compilador
 * @author  gerardo
 */
public class InterfazGrafica extends javax.swing.JFrame {
    
    /** Crea una nueva InterfazGrafica */
    public InterfazGrafica() {
        initComponents();
        this.setBounds(100,100,675,575);
        this.getRootPane().setWindowDecorationStyle(JRootPane.FILE_CHOOSER_DIALOG);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane2 = new javax.swing.JScrollPane();
        tpTexto = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mOpciones = new javax.swing.JMenu();
        mCargar = new javax.swing.JMenuItem();
        mAnalizar = new javax.swing.JMenuItem();
        mGenerar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mSalir = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mMostrar = new javax.swing.JMenuItem();
        mAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 2");
        setResizable(false);
        setUndecorated(true);
        tpTexto.setEditable(false);
        jScrollPane2.setViewportView(tpTexto);

        mOpciones.setText("Opciones");
        mCargar.setText("Cargar");
        mCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCargarActionPerformed(evt);
            }
        });

        mOpciones.add(mCargar);

        mAnalizar.setText("Analizar");
        mAnalizar.setEnabled(false);
        mAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnalizarActionPerformed(evt);
            }
        });

        mOpciones.add(mAnalizar);

        mGenerar.setText("Generar");
        mGenerar.setEnabled(false);
        mGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGenerarActionPerformed(evt);
            }
        });

        mOpciones.add(mGenerar);

        mOpciones.add(jSeparator1);

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });

        mOpciones.add(mSalir);

        jMenuBar1.add(mOpciones);

        mAyuda.setText("Ayuda");
        mMostrar.setText("Abrir archivo");
        mMostrar.setEnabled(false);
        mMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMostrarActionPerformed(evt);
            }
        });

        mAyuda.add(mMostrar);

        mAcercaDe.setText("Acerca De");
        mAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaDeActionPerformed(evt);
            }
        });

        mAyuda.add(mAcercaDe);

        jMenuBar1.add(mAyuda);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 544, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 387, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMostrarActionPerformed
        try{
            String[] comando={"cmd",varArchivo.getAbsolutePath()};
            Process Proceso=Runtime.getRuntime().exec(comando);
            Proceso.waitFor();
        }catch(Exception ex){
            instTool.mensaje(this,ex,"Error de proceso","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mMostrarActionPerformed

    private void mGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGenerarActionPerformed
        instArchivo.GenerarArchivo(this,instAutomata.instCola,instAutomata.instCola_error,instAutomata.tools.vars,instAutomata.tools.varsRepetidas);
    }//GEN-LAST:event_mGenerarActionPerformed

    private void mAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnalizarActionPerformed
        instAutomata=new AutomataP(varArchivo);
        if(instAutomata.Analizar(tpTexto))
            mGenerar.setEnabled(true);
    }//GEN-LAST:event_mAnalizarActionPerformed

    private void mCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCargarActionPerformed
        varArchivo=instArchivo.abrir(this,tpTexto);
        if(varArchivo==null&&bk!=null) varArchivo=bk.getAbsoluteFile();
        
        if(varArchivo!=null){
            mAnalizar.setEnabled(true);
            mMostrar.setEnabled(true);
            bk=varArchivo.getAbsoluteFile();
            mGenerar.setEnabled(false);
        }
        else
            mAnalizar.setEnabled(false);
    }//GEN-LAST:event_mCargarActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        if(instTool.preguntar(this,"Salir?","Salida")) System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void mAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaDeActionPerformed
        instTool.mensaje(this,null,"PROYECTO 2\nHecho por:\nNombre: Gerardo Pineda\nCarnet: 2006-11226","Acerca De",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mAcercaDeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mAcercaDe;
    private javax.swing.JMenuItem mAnalizar;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuItem mCargar;
    private javax.swing.JMenuItem mGenerar;
    private javax.swing.JMenuItem mMostrar;
    private javax.swing.JMenu mOpciones;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JTextPane tpTexto;
    // End of variables declaration//GEN-END:variables
    
    /**Instancia de la clase Tool*/
    Tool instTool=new Tool();
    /**Instancia de la clase Archivo*/
    MArchivo instArchivo=new MArchivo();
    /**Instancia de la clase File. Contiene el archivo que se va a analizar*/
    File varArchivo,bk;
    /**Instancia de la clase Automata*/
    AutomataP instAutomata;
}
