/*
 * Puzzle.java
 *
 * Created on 22 de abril de 2007, 10:11 PM
 */

package Puzzle;

import java.awt.Image;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.*;

/**
 *
 * @author  ONIXX
 */
public class Puzzle extends javax.swing.JFrame {
    final short x=40,w=120,y=50,h=w;
    
    int movs=0;
    byte vacio=8,segs=0,mins=0,hrs=0;
    String carpetaImagen="Imagen1", direccion="/Puzzle/img/" + carpetaImagen + "/c";
    boolean Jterminado=true;
    ImageIcon icono[]=new ImageIcon[9];
    cuadro Cuadro[]=new cuadro[9];
    
    /** Crea un nuevo Puzzle y lo inicializa */
    public Puzzle() {
        initComponents();
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
        ventanaImagenes.setVisible(false);
        Textotmp.setVisible(false);
        scroll.setVisible(false);
        ini();
        
        File tmp = new File("c:/Puzzle");
        if(!tmp.exists()) tmp.mkdir();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Tcronometro = new javax.swing.JTextField();
        Lcronometro = new javax.swing.JLabel();
        Bpausa = new javax.swing.JButton();
        Bdesordenar = new javax.swing.JButton();
        Ltitulo = new javax.swing.JLabel();
        ventanaImagenes = new javax.swing.JPanel();
        Imagen1 = new javax.swing.JLabel();
        Imagen2 = new javax.swing.JLabel();
        Imagen3 = new javax.swing.JLabel();
        Imagen4 = new javax.swing.JLabel();
        Imagen5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Lactual = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        Textotmp = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mAbrir = new javax.swing.JMenuItem();
        mGuardar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mSalir = new javax.swing.JMenuItem();
        mOpciones = new javax.swing.JMenu();
        mImagen = new javax.swing.JMenuItem();
        mDesordenar = new javax.swing.JMenuItem();
        mPuntuaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Puzzle");
        setResizable(false);
        setUndecorated(true);
        Tcronometro.setFont(new java.awt.Font("Tahoma", 0, 24));
        Tcronometro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tcronometro.setText("0:0:0");
        Tcronometro.setFocusable(false);

        Lcronometro.setLabelFor(Tcronometro);
        Lcronometro.setText("Tiempo:");

        Bpausa.setText("Pausar");
        Bpausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpausaActionPerformed(evt);
            }
        });

        Bdesordenar.setText("Desordenar");
        Bdesordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdesordenarActionPerformed(evt);
            }
        });

        Ltitulo.setFont(new java.awt.Font("Tahoma", 0, 24));
        Ltitulo.setText("PUZZLE");

        ventanaImagenes.setBackground(new java.awt.Color(206, 220, 244));
        ventanaImagenes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ventanaImagenes.setPreferredSize(new java.awt.Dimension(400, 400));
        ventanaImagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventanaImagenesMouseClicked(evt);
            }
        });

        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Puzzle/img/Imagen1/ej.jpg")));
        Imagen1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, new java.awt.Color(102, 153, 255)), "Spiderman", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));
        Imagen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Imagen1.setIconTextGap(0);
        Imagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen1MouseClicked(evt);
            }
        });

        Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Puzzle/img/Imagen2/ej.jpg")));
        Imagen2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, new java.awt.Color(102, 153, 255)), "Star Wars", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));
        Imagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Imagen2.setIconTextGap(0);
        Imagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen2MouseClicked(evt);
            }
        });

        Imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Puzzle/img/Imagen3/ej.jpg")));
        Imagen3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, new java.awt.Color(102, 153, 255)), "Metal Gear Solid", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));
        Imagen3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Imagen3.setIconTextGap(0);
        Imagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen3MouseClicked(evt);
            }
        });

        Imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Puzzle/img/Imagen4/ej.jpg")));
        Imagen4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, new java.awt.Color(102, 153, 255)), "Starfish", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));
        Imagen4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Imagen4.setIconTextGap(0);
        Imagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen4MouseClicked(evt);
            }
        });

        Imagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Puzzle/img/Imagen5/ej.jpg")));
        Imagen5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, new java.awt.Color(102, 153, 255)), "Matrix", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));
        Imagen5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Imagen5.setIconTextGap(0);
        Imagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen5MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setLabelFor(Imagen1);
        jLabel1.setText("FACIL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setLabelFor(Imagen2);
        jLabel2.setText("FACIL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setLabelFor(Imagen5);
        jLabel3.setText("DIFICIL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setLabelFor(Imagen4);
        jLabel4.setText("DIFICIL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setLabelFor(Imagen3);
        jLabel5.setText("IMPOSIBLE");

        org.jdesktop.layout.GroupLayout ventanaImagenesLayout = new org.jdesktop.layout.GroupLayout(ventanaImagenes);
        ventanaImagenes.setLayout(ventanaImagenesLayout);
        ventanaImagenesLayout.setHorizontalGroup(
            ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ventanaImagenesLayout.createSequentialGroup()
                .addContainerGap()
                .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ventanaImagenesLayout.createSequentialGroup()
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Imagen1)
                            .add(ventanaImagenesLayout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel5))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, Imagen5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, ventanaImagenesLayout.createSequentialGroup()
                                .add(jLabel3)
                                .add(43, 43, 43)))
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(ventanaImagenesLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(Imagen2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, ventanaImagenesLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel4))
                                .add(32, 32, 32))))
                    .add(ventanaImagenesLayout.createSequentialGroup()
                        .add(Imagen3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 136, Short.MAX_VALUE)
                        .add(Imagen4)))
                .addContainerGap())
        );
        ventanaImagenesLayout.setVerticalGroup(
            ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ventanaImagenesLayout.createSequentialGroup()
                .addContainerGap()
                .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ventanaImagenesLayout.createSequentialGroup()
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Imagen1)
                            .add(Imagen2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 77, Short.MAX_VALUE)
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ventanaImagenesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Imagen3)
                            .add(Imagen4))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ventanaImagenesLayout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Imagen5)
                        .add(145, 145, 145))))
        );

        Lactual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Puzzle/img/Imagen1/ej.jpg")));
        Lactual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setLabelFor(Lactual);
        jLabel7.setText("Actual:");

        scroll.setFocusable(false);
        scroll.setRequestFocusEnabled(false);
        scroll.setWheelScrollingEnabled(false);
        Textotmp.setColumns(20);
        Textotmp.setEditable(false);
        Textotmp.setRows(10);
        Textotmp.setFocusable(false);
        Textotmp.setRequestFocusEnabled(false);
        scroll.setViewportView(Textotmp);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        mArchivo.setText("Archivo");
        mArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mArchivoMouseClicked(evt);
            }
        });

        mAbrir.setText("Abrir");
        mAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAbrirActionPerformed(evt);
            }
        });

        mArchivo.add(mAbrir);

        mGuardar.setText("Guardar");
        mGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarActionPerformed(evt);
            }
        });

        mArchivo.add(mGuardar);

        mArchivo.add(jSeparator2);

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });

        mArchivo.add(mSalir);

        jMenuBar1.add(mArchivo);

        mOpciones.setText("Opciones");
        mOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mOpcionesMouseClicked(evt);
            }
        });

        mImagen.setText("Imagen");
        mImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mImagenActionPerformed(evt);
            }
        });

        mOpciones.add(mImagen);

        mDesordenar.setText("Desordenar");
        mDesordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDesordenarActionPerformed(evt);
            }
        });

        mOpciones.add(mDesordenar);

        mPuntuaciones.setText("Puntuaciones");
        mPuntuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPuntuacionesActionPerformed(evt);
            }
        });

        mOpciones.add(mPuntuaciones);

        jMenuBar1.add(mOpciones);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(ventanaImagenes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 390, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(Lcronometro)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(Bdesordenar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(Bpausa)
                                    .add(Tcronometro)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel7)))
                            .add(Lactual)
                            .add(scroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(166, 166, 166)
                        .add(Ltitulo)))
                .addContainerGap())
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(Ltitulo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(ventanaImagenes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(Lcronometro)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Tcronometro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Bpausa)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Bdesordenar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 63, Short.MAX_VALUE)
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Lactual)
                        .add(57, 57, 57))))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Abre un juego guardado*/
    private void mAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAbrirActionPerformed
        byte i;
        String archivo = tools.abrir(Textotmp);
        if(archivo==null)return;
        
        //cargando datos...
        try{
            //cargando variables...
            BufferedReader input = new BufferedReader(new FileReader(archivo));
            input.readLine();
            Jterminado=Boolean.valueOf(input.readLine());
            carpetaImagen=input.readLine();
            segs=Byte.parseByte(input.readLine());
            mins=Byte.parseByte(input.readLine());
            hrs=Byte.parseByte(input.readLine());
            movs=Integer.parseInt(input.readLine());
        
            //modificando el cronómetro y la dirección de las imágenes...
            Tcronometro.setText(hrs + ":" + mins + ":" + segs);
            direccion="/Puzzle/img/" + carpetaImagen + "/c";

            //cargando iconos...
            for(i=0;i<Cuadro.length;i++){
                icono[(int)i]=null;
                icono[(int)i]=new ImageIcon(getClass().getResource(direccion+i+".jpg"));
            }

            //modificando iconos de los Cuadros y la variable "vacio"...
            for(i=0;i<Cuadro.length;i++){
                Cuadro[(int)i].iconoActual=Byte.parseByte(Textotmp.getText().substring( (int)i , (int)(i+1) ));
                Cuadro[(int)i].setIcon(icono[Cuadro[(int)i].iconoActual]);
            }
            vacio=Byte.parseByte(Textotmp.getText().substring( (int)i , (int)(i+1) ));

            //cargando el icono de la imágen de ejemplo...
            Lactual.setIcon(new ImageIcon(getClass().getResource("/Puzzle/img/" + carpetaImagen + "/ej.jpg")));
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error grave de carga.\n"+ex.getMessage()+"\nEl archivo no es válido:\n\n"+
            Textotmp.getText()+"\n\nEl juego se va a cerrar","Error Grave",JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_mAbrirActionPerformed

    /**Guarda un juego*/
    private void mGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarActionPerformed
        tools.guardar(Cuadro,vacio,Jterminado,carpetaImagen,segs,mins,hrs,movs);
    }//GEN-LAST:event_mGuardarActionPerformed

    /**Abre la ventana de puntuaciones*/
    private void mPuntuacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPuntuacionesActionPerformed
        tools.setVisible(true);
        tools.cargarPuntuaciones();
    }//GEN-LAST:event_mPuntuacionesActionPerformed

    /**Sale al menu principal*/
    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        JOptionPane pane=new JOptionPane("Salir al menu?",JOptionPane.QUESTION_MESSAGE,JOptionPane.YES_NO_OPTION);
        JDialog dialog=pane.createDialog(this,"Salida");
        dialog.setDefaultCloseOperation(dialog.DO_NOTHING_ON_CLOSE);
        dialog.setVisible(true);
        Object s=pane.getValue();
        if(((Integer)s).intValue()==pane.NO_OPTION)return;
        else this.dispose();
    }//GEN-LAST:event_mSalirActionPerformed

    private void mOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mOpcionesMouseClicked
        Bpausa.doClick();
    }//GEN-LAST:event_mOpcionesMouseClicked

    private void mArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mArchivoMouseClicked
        Bpausa.doClick();
    }//GEN-LAST:event_mArchivoMouseClicked

    private void mDesordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDesordenarActionPerformed
        Bdesordenar.doClick();
    }//GEN-LAST:event_mDesordenarActionPerformed

    private void Imagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen5MouseClicked
        carpetaImagen="Imagen5";
        cambiarImagen();
        ventanaImagenes.setVisible(false);
        Lactual.setIcon(Imagen5.getIcon());
    }//GEN-LAST:event_Imagen5MouseClicked

    private void Imagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen4MouseClicked
        carpetaImagen="Imagen4";
        cambiarImagen();
        ventanaImagenes.setVisible(false);
        Lactual.setIcon(Imagen4.getIcon());
    }//GEN-LAST:event_Imagen4MouseClicked

    private void Imagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen3MouseClicked
        carpetaImagen="Imagen3";
        cambiarImagen();
        ventanaImagenes.setVisible(false);
        Lactual.setIcon(Imagen3.getIcon());
    }//GEN-LAST:event_Imagen3MouseClicked

    private void Imagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen2MouseClicked
        carpetaImagen="Imagen2";
        cambiarImagen();
        ventanaImagenes.setVisible(false);
        Lactual.setIcon(Imagen2.getIcon());
    }//GEN-LAST:event_Imagen2MouseClicked

    private void ventanaImagenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventanaImagenesMouseClicked
        Bpausa.doClick();
    }//GEN-LAST:event_ventanaImagenesMouseClicked

    private void Imagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen1MouseClicked
        carpetaImagen="Imagen1";
        cambiarImagen();
        ventanaImagenes.setVisible(false);
        Lactual.setIcon(Imagen1.getIcon());
    }//GEN-LAST:event_Imagen1MouseClicked

    private void mImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mImagenActionPerformed
        Bpausa.doClick();
        if(!preguntar("Si se escoge otra imágen el juego se va a reiniciar.\nEscoger otra imágen?","Advertencia!"))
            return;
        
        Jterminado=true;
        ventanaImagenes.setVisible(true);
        nuevoJuego();
    }//GEN-LAST:event_mImagenActionPerformed

    /**Desordena las imágenes para empezar un nuevo juego (si el jugador
     * lo aprueba)
     */
    private void BdesordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdesordenarActionPerformed
        if(Jterminado==false){
            if(cronometro.isRunning())
                cronometro.stop();
            if(!preguntar("El juego se va a reiniciar al desordenar las imágenes.\nDesordenar?","Advertencia!"))
                return;
        }
        
        byte num=0,tmp;
        Ppila temp=new Ppila();
        
        for(byte i=0;i<Cuadro.length;i++){
            num=((tmp=(byte)(Math.random()*10))<9)?tmp:num;
            while(temp.esRepetido(num))
                num=((tmp=(byte)(Math.random()*10))<9)?tmp:num;
            
            temp.push(num);
            Cuadro[(int)i].setIcon(icono[(int)num]);
            Cuadro[(int)i].iconoActual=num;
            //"num" es el índice de icono[] y "i" es el índice de Cuadro[],
            // entonces, si está seleccionada la imagen vacia (num==8), vacio=i.
            //Siempre recordar que la imagen vacia SIEMPRE esta en el índice 8.
            vacio=(num==8)?i:vacio;
        }
        nuevoJuego();
    }//GEN-LAST:event_BdesordenarActionPerformed

    /**Pausa el juego hasta que el jugador mueva las imágenes*/
    private void BpausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpausaActionPerformed
        if(cronometro.isRunning())
                cronometro.stop();
    }//GEN-LAST:event_BpausaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puzzle().setVisible(true);
            }
        });
    }
    
    /**Metodo que se ejecuta al hacer clic a una imagen.
     *Enciende el cronómetro*/
    private void CuadroMouseClicked(java.awt.event.MouseEvent evt) {
        for(byte i=0;i<Cuadro.length;i++)
            if(evt.getSource().equals(Cuadro[(int)i])){
                mover(Cuadro[(int)i],i);
                break;
            }
    }

    /**Método que valida cuál es el cuadro que se tiene que mover.
     *Invoca al método Proceso para mover el cuadro*/
    private void mover(cuadro cuad,byte posActual) {
        cuadro temp=new cuadro();
        
        if(vacio==posActual+3||vacio==posActual-3)
            Proceso(temp,cuad,posActual);
        else
            if(posActual!=2 && posActual!=5 && posActual!=8 && vacio==posActual+1)
                Proceso(temp,cuad,posActual);
            else
                if(posActual!=0 && posActual!=3 && posActual!=6 && vacio==posActual-1)
                    Proceso(temp,cuad,posActual);
                
        byte aux=0;
        for(byte i=0;i<Cuadro.length;i++)
            if(Cuadro[(int)i].getIcon()!=icono[(int)i])
                break;
            else
                aux++;
        
        if(aux==9)TerminarJuego();
            
        //JOptionPane.showMessageDialog(this,cuad.getIcon());
    }

    /**Inicializa los objetos icono y Cuadro, y asigna el icono a cada
     * Cuadro. También asigna vacio=8 porque esa posición tiene el Cuadro que
     * está vacío al inicializarse.
     */
    private void ini() {
        byte temp=0;
        for(byte i=0;i<3;i++)
            for(byte j=0;j<3;j++){
                icono[(int)temp]=new ImageIcon(getClass().getResource(direccion+temp+".jpg"));
                Cuadro[(int)temp]=new cuadro(temp,(short)(x+(i*w)),(short)(y+(j*h)),icono[(int)temp]);
                Cuadro[(int)temp].setBounds(Cuadro[(int)temp].x,Cuadro[(int)temp].y,w,h);
                add(Cuadro[(int)temp]);
                
                Cuadro[(int)temp].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        CuadroMouseClicked(evt);
                    }
                });
                
                Cuadro[(int)temp++].setVisible(true);
            }
        vacio=8;
        Bdesordenar.doClick();
    }

    /**Mueve el cuadro en donde se originó el evento y cambia el valor a vacio.
     *Si el cronómetro está detenido, lo inicia
     */
    private void Proceso(cuadro Temp, cuadro Cuad, byte PosActual) {
        if(!Jterminado){
            if(!cronometro.isRunning())
                cronometro.start();
            
            Temp.setIcon(Cuadro[(int)vacio].getIcon());
            Temp.iconoActual=Cuadro[(int)vacio].iconoActual;
            
            Cuadro[(int)vacio].setIcon(Cuad.getIcon());
            Cuadro[(int)vacio].iconoActual=Cuad.iconoActual;
            
            Cuad.setIcon(Temp.getIcon());
            Cuad.iconoActual=Temp.iconoActual;
            
            vacio=PosActual;
            movs++;
        }
    }
    
    /**Es el cuerpo del cronómetro. Lleva el control del tiempo.*/
    public void correrTiempo() {
        if(++segs==60){
            segs=0;
            if(++mins==60){
                mins=0;
                hrs++;
            }
        }
        Tcronometro.setText(hrs + ":" + mins + ":" + segs);
    }

    /**Método que termina el juego porque el jugador ganó.
     *Detiene el cronómetro, bloquea el tablero y pide el nombre al jugador
     * para ponerlos en los puntajes altos si es que lo merece.*/
    private void TerminarJuego() {
        Bpausa.doClick();
        JOptionPane.showMessageDialog(this,"COMPLETO!!","Fin del juego",JOptionPane.INFORMATION_MESSAGE);
        
        if(!Jterminado){
            Jterminado=true;
            
            JTextField text=new JTextField();
            Object[] array={"Nombre:",text};
            JOptionPane pane=new JOptionPane(array,JOptionPane.QUESTION_MESSAGE,-1);
            JDialog dialog=pane.createDialog(this,"Nombre del jugador");
            dialog.setDefaultCloseOperation(dialog.DO_NOTHING_ON_CLOSE);
            dialog.setVisible(true);
            Object s=pane.getValue();
            if(s==null){}
            else{
                //puntajes altos y reportes:
                tools.ponerEnPuntajes(text.getText(),Tcronometro.getText(),carpetaImagen,movs);
                tools.reportar(movs,Tcronometro.getText(),carpetaImagen,text.getText());
            }
        }
        
    }

    /**Pone el cronometro y los contadores en 0 y asigna false a la variable
     * Jterminado
     */
    private void nuevoJuego() {
        movs=hrs=mins=segs=0;
        Tcronometro.setText(hrs + ":" + mins + ":" + segs);
        Jterminado=false;
    }

    /**Asigna una nueva imagen a cada icono y despues le asigna a cada
     * Cuadro un icono, en la posición que corresponde cada icono.
     *Detiene el cronómetro y asigna true a Jterminado para que al llamar al
     * método que desordena las imágenes no se pida la confirmación de un nuevo
     *  juego; después se ejecuta nuevoJuego y asigna false a Jterminado.
     */
    private void cambiarImagen() {
        direccion="/Puzzle/img/" + carpetaImagen + "/c";
        for(byte temp=0;temp<Cuadro.length;temp++){
            icono[(int)temp]=null;
            icono[(int)temp]=new ImageIcon(getClass().getResource(direccion+temp+".jpg"));
            Cuadro[(int)temp].setIcon(icono[(int)temp]);
        }
        //No es necesario escribir vacio=8 porque el método que desordena las
        //imágenes asigna: vacio=(índice del cuadro le asignó la imágen vacía).
        Jterminado=true;
        Bpausa.doClick();
        Bdesordenar.doClick();
    }

    /**Solo es un JOptionPane que despliega una pregunta y toma el valor que el
     * jugador escoge
     */
    private boolean preguntar(String mensaje, String titulo) {
        JOptionPane pane=new JOptionPane(mensaje,JOptionPane.QUESTION_MESSAGE,JOptionPane.YES_NO_OPTION);
        JDialog dialog=pane.createDialog(this,titulo);
        dialog.setDefaultCloseOperation(dialog.DO_NOTHING_ON_CLOSE);
        dialog.setVisible(true);
        Object s=pane.getValue();
        if(((Integer)s).intValue()==pane.NO_OPTION)return false;
        else return true;
    }
    
    

    Timer cronometro = new Timer(1000,new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                correrTiempo();
            }
        });
        
        /**Crea una nueva clase Ptools que tiene todos los metodos que tienen
         * que ver con archivos (abrir, etc..) y su interfaz gráfica despliega
         * el listado de los 10 mejores jugadores
         */
        Ptools tools = new Ptools();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdesordenar;
    private javax.swing.JButton Bpausa;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JLabel Imagen3;
    private javax.swing.JLabel Imagen4;
    private javax.swing.JLabel Imagen5;
    private javax.swing.JLabel Lactual;
    private javax.swing.JLabel Lcronometro;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JTextField Tcronometro;
    private javax.swing.JTextArea Textotmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem mAbrir;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mDesordenar;
    private javax.swing.JMenuItem mGuardar;
    private javax.swing.JMenuItem mImagen;
    private javax.swing.JMenu mOpciones;
    private javax.swing.JMenuItem mPuntuaciones;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel ventanaImagenes;
    // End of variables declaration//GEN-END:variables
    
}
