/*
 * Hanoi.java
 *
 * Created on 15 de abril de 2007, 03:05 PM
 */

package Hanoi;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author  ONIXX
 */
public class Hanoi extends javax.swing.JFrame {
    
    /** Creates new form Hanoi */
    public Hanoi() {
        initComponents();
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        LnumAros = new javax.swing.JLabel();
        TnumAros = new javax.swing.JTextField();
        Bempezar = new javax.swing.JButton();
        Bguardar = new javax.swing.JButton();
        Bpausa = new javax.swing.JButton();
        Tcronometro = new javax.swing.JTextField();
        Ltiempo = new javax.swing.JLabel();
        Ltitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Torre1 = new javax.swing.JLabel();
        Torre2 = new javax.swing.JLabel();
        Torre3 = new javax.swing.JLabel();
        Lt1 = new javax.swing.JLabel();
        Lt2 = new javax.swing.JLabel();
        Lt3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuCargar = new javax.swing.JMenuItem();
        menuRecords = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuSalir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuReglas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Torres de Hanoi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setUndecorated(true);
        LnumAros.setLabelFor(TnumAros);
        LnumAros.setText("Numero de discos:");

        Bempezar.setText("Empezar Nuevo");

        Bguardar.setText("Guardar Juego");

        Bpausa.setText("Pausa");

        Tcronometro.setFont(new java.awt.Font("Tahoma", 0, 24));
        Tcronometro.setText("00:00:00");
        Tcronometro.setAutoscrolls(false);
        Tcronometro.setFocusable(false);

        Ltiempo.setLabelFor(Tcronometro);
        Ltiempo.setText("Tiempo:");

        Ltitulo.setFont(new java.awt.Font("Tahoma", 0, 24));
        Ltitulo.setLabelFor(jPanel1);
        Ltitulo.setText("TORRES DE HANOI");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        Torre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hanoi/img/Torre.jpg")));
        Torre1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Torre1MouseDragged(evt);
            }
        });

        Torre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hanoi/img/Torre.jpg")));

        Torre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hanoi/img/Torre.jpg")));

        Lt1.setFont(new java.awt.Font("Tahoma", 1, 14));
        Lt1.setForeground(new java.awt.Color(204, 102, 0));
        Lt1.setLabelFor(Torre1);
        Lt1.setText("TORRE 1");

        Lt2.setFont(new java.awt.Font("Tahoma", 1, 14));
        Lt2.setForeground(new java.awt.Color(204, 102, 0));
        Lt2.setLabelFor(Torre2);
        Lt2.setText("TORRE 2");

        Lt3.setFont(new java.awt.Font("Tahoma", 1, 14));
        Lt3.setForeground(new java.awt.Color(204, 102, 0));
        Lt3.setLabelFor(Torre3);
        Lt3.setText("TORRE 3");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(Torre1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(Lt1)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(Torre2)
                        .add(25, 25, 25))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(Lt2)
                        .add(70, 70, 70)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Torre3)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(Lt3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Torre1)
                    .add(Torre3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Lt1)
                    .add(Lt3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .add(Torre2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Lt2)
                .addContainerGap())
        );

        menuOpciones.setText("Opciones");
        menuCargar.setText("Cargar");
        menuOpciones.add(menuCargar);

        menuRecords.setText("Puntajes Altos");
        menuOpciones.add(menuRecords);

        menuOpciones.add(jSeparator1);

        menuSalir.setText("Salir al menu");
        menuOpciones.add(menuSalir);

        jMenuBar1.add(menuOpciones);

        menuAyuda.setText("Ayuda");
        menuReglas.setText("Reglas del Juego");
        menuAyuda.add(menuReglas);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(30, 30, 30)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Bempezar)
                            .add(layout.createSequentialGroup()
                                .add(LnumAros)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TnumAros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(Tcronometro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Ltiempo)
                            .add(Bpausa)
                            .add(Bguardar)))
                    .add(layout.createSequentialGroup()
                        .add(199, 199, 199)
                        .add(Ltitulo)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(Ltitulo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(Ltiempo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Tcronometro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(Bguardar)
                        .add(17, 17, 17)
                        .add(Bpausa)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 150, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(LnumAros)
                            .add(TnumAros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Bempezar)
                        .add(57, 57, 57))))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Torre1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Torre1MouseDragged
        //para cada disco:
        /*Point p = jPanel1.getMousePosition();
        try{
            evt.getComponent().setLocation(p);
        }catch(NullPointerException ex){regresar a pos inicial}*/
    }//GEN-LAST:event_Torre1MouseDragged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hanoi().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bempezar;
    private javax.swing.JButton Bguardar;
    private javax.swing.JButton Bpausa;
    private javax.swing.JLabel LnumAros;
    private javax.swing.JLabel Lt1;
    private javax.swing.JLabel Lt2;
    private javax.swing.JLabel Lt3;
    private javax.swing.JLabel Ltiempo;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JTextField Tcronometro;
    private javax.swing.JTextField TnumAros;
    private javax.swing.JLabel Torre1;
    private javax.swing.JLabel Torre2;
    private javax.swing.JLabel Torre3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuCargar;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem menuRecords;
    private javax.swing.JMenuItem menuReglas;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
    
}
