--
-- ER/Studio 7.1 SQL Code Generation
-- Company :      .
-- Project :      Modelo.dm1
-- Author :       gerardo
--
-- Date Created : Wednesday, April 24, 2013 15:55:05
-- Target DBMS : Oracle 10g
--

DROP TABLE CARGAMENTO CASCADE CONSTRAINTS
;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS
;
DROP TABLE COTIZACION CASCADE CONSTRAINTS
;
DROP TABLE DETALLECOTIZACION CASCADE CONSTRAINTS
;
DROP TABLE DETALLEVENTA CASCADE CONSTRAINTS
;
DROP TABLE DEVOLUCIONINGRESO CASCADE CONSTRAINTS
;
DROP TABLE DEVOLUCIONVENTA CASCADE CONSTRAINTS
;
DROP TABLE ESTADO CASCADE CONSTRAINTS
;
DROP TABLE INGRESO CASCADE CONSTRAINTS
;
DROP TABLE LOTE CASCADE CONSTRAINTS
;
DROP TABLE MONEDA CASCADE CONSTRAINTS
;
DROP TABLE OFERTA CASCADE CONSTRAINTS
;
DROP TABLE OFERTACOTIZACION CASCADE CONSTRAINTS
;
DROP TABLE PERSONA CASCADE CONSTRAINTS
;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS
;
DROP TABLE TARJETA CASCADE CONSTRAINTS
;
DROP TABLE TIPOENTREGA CASCADE CONSTRAINTS
;
DROP TABLE TIPOOFERTA CASCADE CONSTRAINTS
;
DROP TABLE TIPOOPERACION CASCADE CONSTRAINTS
;
DROP TABLE TIPOPAGO CASCADE CONSTRAINTS
;
DROP TABLE TIPOPERSONA CASCADE CONSTRAINTS
;
DROP TABLE TIPOTARJETA CASCADE CONSTRAINTS
;
DROP TABLE TIPOUNIDAD CASCADE CONSTRAINTS
;
DROP TABLE VENTA CASCADE CONSTRAINTS
;