--
-- ER/Studio 7.1 SQL Code Generation
-- Company :      .
-- Project :      Modelo.dm1
-- Author :       gerardo
--
-- Date Created : Wednesday, May 01, 2013 13:36:04
-- Target DBMS : Oracle 10g
--

-- 
-- TABLE: CARGAMENTO 
--

CREATE TABLE CARGAMENTO(
    IDCARGAMENTO              VARCHAR2(50)     NOT NULL,
    FECHAINGRESOINVENTARIO    VARCHAR2(20)     NOT NULL,
    CANTIDADLOTES             NUMBER(10, 0),
    CARGAMENTORECIBIDO        VARCHAR2(25),
    MANIFIESTO                NUMBER(20, 0),
    RECIBIDOPOR               NUMBER(10, 0)    NOT NULL,
    DELEGADO                  NUMBER(10, 0)    NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: CATEGORIA 
--

CREATE TABLE CATEGORIA(
    IDCATEGORIA    NUMBER(10, 0)    NOT NULL,
    IDPADRE        NUMBER(10, 0)    NOT NULL,
    NOMBRE         VARCHAR2(50)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: COTIZACION 
--

CREATE TABLE COTIZACION(
    IDCOTIZACION         NUMBER(15, 0)     NOT NULL,
    FECHACOTIZACION      VARCHAR2(20)      NOT NULL,
    IDESTADO             NUMBER(10, 0)     NOT NULL,
    TOTAL                NUMBER(31, 25),
    JUSTIFICACION        VARCHAR2(100),
    CODIGOAPROBACION     VARCHAR2(50),
    IDMONEDA             NUMBER(10, 0)     NOT NULL,
    IDTIPOOPER           NUMBER(10, 0)     NOT NULL,
    IDTIPOPAGO           NUMBER(10, 0)     NOT NULL,
    SOLICITANTE          NUMBER(10, 0)     NOT NULL,
    CREADOR              NUMBER(10, 0)     NOT NULL,
    FIRMAAUTORIZACION    NUMBER(10, 0)     NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: DETALLECOTIZACION 
--

CREATE TABLE DETALLECOTIZACION(
    FECHADETALLE       VARCHAR2(20)      NOT NULL,
    IDPRODUCTO         NUMBER(10, 0)     NOT NULL,
    IDCOTIZACION       NUMBER(15, 0)     NOT NULL,
    FECHACOTIZACION    VARCHAR2(20)      NOT NULL,
    IDESTADO           NUMBER(10, 0)     NOT NULL,
    CANTIDAD           NUMBER(6, 0),
    FECHAENTREGA       VARCHAR2(20),
    PRECIOUNITARIO     NUMBER(31, 25),
    IDMONEDA           NUMBER(10, 0)     NOT NULL,
    SUBTOTAL           NUMBER(31, 25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: DETALLEVENTA 
--

CREATE TABLE DETALLEVENTA(
    IDDETALLE                 NUMBER(10, 0)     NOT NULL,
    IDVENTA                   NUMBER(10, 0)     NOT NULL,
    FECHA                     VARCHAR2(20)      NOT NULL,
    IDINGRESO                 NUMBER(10, 0)     NOT NULL,
    IDLOTE                    NUMBER(10, 0)     NOT NULL,
    IDCARGAMENTO              VARCHAR2(50)      NOT NULL,
    FECHAINGRESOINVENTARIO    VARCHAR2(20)      NOT NULL,
    IDPRODUCTO                NUMBER(10, 0)     NOT NULL,
    PRECIO                    NUMBER(31, 25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: DEVOLUCIONINGRESO 
--

CREATE TABLE DEVOLUCIONINGRESO(
    IDINGRESO                 NUMBER(10, 0)    NOT NULL,
    IDLOTE                    NUMBER(10, 0)    NOT NULL,
    IDCARGAMENTO              VARCHAR2(50)     NOT NULL,
    FECHAINGRESOINVENTARIO    VARCHAR2(20)     NOT NULL,
    IDPRODUCTO                NUMBER(10, 0)    NOT NULL,
    FECHADEVOLUCION           VARCHAR2(20),
    IDCATEGORIA               NUMBER(10, 0)    NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: DEVOLUCIONVENTA 
--

CREATE TABLE DEVOLUCIONVENTA(
    IDDEVOLVENTA       NUMBER(10, 0)    NOT NULL,
    IDDETALLE          NUMBER(10, 0)    NOT NULL,
    IDVENTA            NUMBER(10, 0)    NOT NULL,
    FECHA              VARCHAR2(20)     NOT NULL,
    FECHADEVOLUCION    VARCHAR2(20)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: ESTADO 
--

CREATE TABLE ESTADO(
    IDESTADO    NUMBER(10, 0)    NOT NULL,
    NOMBRE      VARCHAR2(25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: INGRESO 
--

CREATE TABLE INGRESO(
    IDINGRESO                 NUMBER(10, 0)    NOT NULL,
    IDLOTE                    NUMBER(10, 0)    NOT NULL,
    IDCARGAMENTO              VARCHAR2(50)     NOT NULL,
    FECHAINGRESOINVENTARIO    VARCHAR2(20)     NOT NULL,
    IDPRODUCTO                NUMBER(10, 0)    NOT NULL,
    NOCAJA                    NUMBER(10, 0),
    IDOFERTA                  NUMBER(10, 0)    NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: LOTE 
--

CREATE TABLE LOTE(
    IDLOTE                    NUMBER(10, 0)    NOT NULL,
    IDCARGAMENTO              VARCHAR2(50)     NOT NULL,
    FECHAINGRESOINVENTARIO    VARCHAR2(20)     NOT NULL,
    FECHAPRODUCCION           VARCHAR2(20),
    FECHAEXPIRACION           VARCHAR2(20),
    CANTIDADCAJAS             NUMBER(10, 0)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: MONEDA 
--

CREATE TABLE MONEDA(
    IDMONEDA      NUMBER(10, 0)    NOT NULL,
    NOMBRE        VARCHAR2(50),
    SIMBOLO       VARCHAR2(10),
    TIPOCAMBIO    NUMBER(10, 0)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: OFERTA 
--

CREATE TABLE OFERTA(
    IDOFERTA        NUMBER(10, 0)     NOT NULL,
    CONDICION       VARCHAR2(100),
    VALOR           NUMBER(31, 25),
    IDTIPOOFERTA    NUMBER(10, 0)     NOT NULL,
    IDTIPOUNIDAD    NUMBER(10, 0)     NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: OFERTACOTIZACION 
--

CREATE TABLE OFERTACOTIZACION(
    IDCOTIZACION       NUMBER(15, 0)    NOT NULL,
    IDOFERTA           NUMBER(10, 0)    NOT NULL,
    FECHACOTIZACION    VARCHAR2(20)     NOT NULL,
    IDESTADO           NUMBER(10, 0)    NOT NULL,
    FECHAINICIO        VARCHAR2(20),
    FECHAFIN           VARCHAR2(20)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: PERSONA 
--

CREATE TABLE PERSONA(
    IDPERSONA               NUMBER(10, 0)    NOT NULL,
    NIT                     VARCHAR2(20),
    NOMBRE                  VARCHAR2(50),
    APELLIDO                VARCHAR2(50),
    EDAD                    NUMBER(3, 0),
    SEXO                    VARCHAR2(15),
    DIRECCIONENTREGA        VARCHAR2(100),
    DIRECCIONFACTURACION    VARCHAR2(100),
    IDTIPOPERSONA           NUMBER(10, 0)    NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: PRODUCTO 
--

CREATE TABLE PRODUCTO(
    IDPRODUCTO       NUMBER(10, 0)     NOT NULL,
    NOMBRE           VARCHAR2(50),
    COSTOUNITARIO    NUMBER(31, 25),
    EXISTENCIA       NUMBER(10, 0),
    IDCATEGORIA      NUMBER(10, 0)     NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    NOTARJETA             VARCHAR2(50)     NOT NULL,
    IDPERSONA             NUMBER(10, 0)    NOT NULL,
    LIMITE                NUMBER(10, 0),
    CODIGOAUTORIZACION    VARCHAR2(50),
    IDTIPOTARJETA         NUMBER(10, 0)    NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOENTREGA 
--

CREATE TABLE TIPOENTREGA(
    IDTIPOENTREGA    NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(50)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOOFERTA 
--

CREATE TABLE TIPOOFERTA(
    IDTIPOOFERTA    NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOOPERACION 
--

CREATE TABLE TIPOOPERACION(
    IDTIPOOPER    NUMBER(10, 0)    NOT NULL,
    NOMBRE        VARCHAR2(50)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOPAGO 
--

CREATE TABLE TIPOPAGO(
    IDTIPOPAGO    NUMBER(10, 0)    NOT NULL,
    NOMBRE        VARCHAR2(25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOPERSONA 
--

CREATE TABLE TIPOPERSONA(
    IDTIPOPERSONA    NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOTARJETA 
--

CREATE TABLE TIPOTARJETA(
    IDTIPOTARJETA    NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(25)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: TIPOUNIDAD 
--

CREATE TABLE TIPOUNIDAD(
    IDTIPOUNIDAD    NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(5)
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: VENTA 
--

CREATE TABLE VENTA(
    IDVENTA          NUMBER(10, 0)     NOT NULL,
    FECHA            VARCHAR2(20)      NOT NULL,
    TOTAL            NUMBER(31, 25),
    IDTIPOENTREGA    NUMBER(10, 0)     NOT NULL,
    IDTIPOPAGO       NUMBER(10, 0)     NOT NULL,
    NODOCPAGO        VARCHAR2(50),
    NOTARJETA        VARCHAR2(50)      NOT NULL,
    IDPERSONA        NUMBER(10, 0)     NOT NULL
)
TABLESPACE ts_bases1
;



-- 
-- TABLE: CARGAMENTO 
--

ALTER TABLE CARGAMENTO ADD 
    CONSTRAINT PK6 PRIMARY KEY (IDCARGAMENTO, FECHAINGRESOINVENTARIO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: CATEGORIA 
--

ALTER TABLE CATEGORIA ADD 
    CONSTRAINT PK8 PRIMARY KEY (IDCATEGORIA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: COTIZACION 
--

ALTER TABLE COTIZACION ADD 
    CONSTRAINT PK11 PRIMARY KEY (IDCOTIZACION, FECHACOTIZACION, IDESTADO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: DETALLECOTIZACION 
--

ALTER TABLE DETALLECOTIZACION ADD 
    CONSTRAINT PK1 PRIMARY KEY (FECHADETALLE, IDPRODUCTO, IDCOTIZACION, FECHACOTIZACION, IDESTADO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: DETALLEVENTA 
--

ALTER TABLE DETALLEVENTA ADD 
    CONSTRAINT PK15 PRIMARY KEY (IDDETALLE, IDVENTA, FECHA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: DEVOLUCIONINGRESO 
--

ALTER TABLE DEVOLUCIONINGRESO ADD 
    CONSTRAINT PK17 PRIMARY KEY (IDINGRESO, IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO, IDPRODUCTO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: DEVOLUCIONVENTA 
--

ALTER TABLE DEVOLUCIONVENTA ADD 
    CONSTRAINT PK21 PRIMARY KEY (IDDEVOLVENTA, IDDETALLE, IDVENTA, FECHA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: ESTADO 
--

ALTER TABLE ESTADO ADD 
    CONSTRAINT PK25 PRIMARY KEY (IDESTADO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: INGRESO 
--

ALTER TABLE INGRESO ADD 
    CONSTRAINT PK10 PRIMARY KEY (IDINGRESO, IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO, IDPRODUCTO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: LOTE 
--

ALTER TABLE LOTE ADD 
    CONSTRAINT PK7 PRIMARY KEY (IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: MONEDA 
--

ALTER TABLE MONEDA ADD 
    CONSTRAINT PK3 PRIMARY KEY (IDMONEDA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: OFERTA 
--

ALTER TABLE OFERTA ADD 
    CONSTRAINT PK2 PRIMARY KEY (IDOFERTA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: OFERTACOTIZACION 
--

ALTER TABLE OFERTACOTIZACION ADD 
    CONSTRAINT PK12 PRIMARY KEY (IDCOTIZACION, IDOFERTA, FECHACOTIZACION, IDESTADO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: PERSONA 
--

ALTER TABLE PERSONA ADD 
    CONSTRAINT PK13 PRIMARY KEY (IDPERSONA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: PRODUCTO 
--

ALTER TABLE PRODUCTO ADD 
    CONSTRAINT PK5 PRIMARY KEY (IDPRODUCTO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TARJETA 
--

ALTER TABLE TARJETA ADD 
    CONSTRAINT PK26 PRIMARY KEY (NOTARJETA, IDPERSONA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOENTREGA 
--

ALTER TABLE TIPOENTREGA ADD 
    CONSTRAINT PK22 PRIMARY KEY (IDTIPOENTREGA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOOFERTA 
--

ALTER TABLE TIPOOFERTA ADD 
    CONSTRAINT PK23 PRIMARY KEY (IDTIPOOFERTA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOOPERACION 
--

ALTER TABLE TIPOOPERACION ADD 
    CONSTRAINT PK18 PRIMARY KEY (IDTIPOOPER)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOPAGO 
--

ALTER TABLE TIPOPAGO ADD 
    CONSTRAINT PK20 PRIMARY KEY (IDTIPOPAGO)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOPERSONA 
--

ALTER TABLE TIPOPERSONA ADD 
    CONSTRAINT PK29 PRIMARY KEY (IDTIPOPERSONA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOTARJETA 
--

ALTER TABLE TIPOTARJETA ADD 
    CONSTRAINT PK28 PRIMARY KEY (IDTIPOTARJETA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: TIPOUNIDAD 
--

ALTER TABLE TIPOUNIDAD ADD 
    CONSTRAINT PK24 PRIMARY KEY (IDTIPOUNIDAD)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: VENTA 
--

ALTER TABLE VENTA ADD 
    CONSTRAINT PK14 PRIMARY KEY (IDVENTA, FECHA)
    USING INDEX
TABLESPACE ts_bases1
;

-- 
-- TABLE: CARGAMENTO 
--

ALTER TABLE CARGAMENTO ADD CONSTRAINT RefPERSONA51 
    FOREIGN KEY (RECIBIDOPOR)
    REFERENCES PERSONA(IDPERSONA)
;

ALTER TABLE CARGAMENTO ADD CONSTRAINT RefPERSONA52 
    FOREIGN KEY (DELEGADO)
    REFERENCES PERSONA(IDPERSONA)
;


-- 
-- TABLE: CATEGORIA 
--

ALTER TABLE CATEGORIA ADD CONSTRAINT RefCATEGORIA30 
    FOREIGN KEY (IDPADRE)
    REFERENCES CATEGORIA(IDCATEGORIA)
;


-- 
-- TABLE: COTIZACION 
--

ALTER TABLE COTIZACION ADD CONSTRAINT RefESTADO43 
    FOREIGN KEY (IDESTADO)
    REFERENCES ESTADO(IDESTADO)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefTIPOPAGO44 
    FOREIGN KEY (IDTIPOPAGO)
    REFERENCES TIPOPAGO(IDTIPOPAGO)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefPERSONA53 
    FOREIGN KEY (SOLICITANTE)
    REFERENCES PERSONA(IDPERSONA)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefPERSONA54 
    FOREIGN KEY (CREADOR)
    REFERENCES PERSONA(IDPERSONA)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefPERSONA55 
    FOREIGN KEY (FIRMAAUTORIZACION)
    REFERENCES PERSONA(IDPERSONA)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefMONEDA27 
    FOREIGN KEY (IDMONEDA)
    REFERENCES MONEDA(IDMONEDA)
;

ALTER TABLE COTIZACION ADD CONSTRAINT RefTIPOOPERACION28 
    FOREIGN KEY (IDTIPOOPER)
    REFERENCES TIPOOPERACION(IDTIPOOPER)
;


-- 
-- TABLE: DETALLECOTIZACION 
--

ALTER TABLE DETALLECOTIZACION ADD CONSTRAINT RefMONEDA2 
    FOREIGN KEY (IDMONEDA)
    REFERENCES MONEDA(IDMONEDA)
;

ALTER TABLE DETALLECOTIZACION ADD CONSTRAINT RefPRODUCTO15 
    FOREIGN KEY (IDPRODUCTO)
    REFERENCES PRODUCTO(IDPRODUCTO)
;

ALTER TABLE DETALLECOTIZACION ADD CONSTRAINT RefCOTIZACION17 
    FOREIGN KEY (IDCOTIZACION, FECHACOTIZACION, IDESTADO)
    REFERENCES COTIZACION(IDCOTIZACION, FECHACOTIZACION, IDESTADO)
;


-- 
-- TABLE: DETALLEVENTA 
--

ALTER TABLE DETALLEVENTA ADD CONSTRAINT RefVENTA21 
    FOREIGN KEY (IDVENTA, FECHA)
    REFERENCES VENTA(IDVENTA, FECHA)
;

ALTER TABLE DETALLEVENTA ADD CONSTRAINT RefINGRESO38 
    FOREIGN KEY (IDINGRESO, IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO, IDPRODUCTO)
    REFERENCES INGRESO(IDINGRESO, IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO, IDPRODUCTO)
;


-- 
-- TABLE: DEVOLUCIONINGRESO 
--

ALTER TABLE DEVOLUCIONINGRESO ADD CONSTRAINT RefCATEGORIA33 
    FOREIGN KEY (IDCATEGORIA)
    REFERENCES CATEGORIA(IDCATEGORIA)
;

ALTER TABLE DEVOLUCIONINGRESO ADD CONSTRAINT RefINGRESO35 
    FOREIGN KEY (IDINGRESO, IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO, IDPRODUCTO)
    REFERENCES INGRESO(IDINGRESO, IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO, IDPRODUCTO)
;


-- 
-- TABLE: DEVOLUCIONVENTA 
--

ALTER TABLE DEVOLUCIONVENTA ADD CONSTRAINT RefDETALLEVENTA39 
    FOREIGN KEY (IDDETALLE, IDVENTA, FECHA)
    REFERENCES DETALLEVENTA(IDDETALLE, IDVENTA, FECHA)
;


-- 
-- TABLE: INGRESO 
--

ALTER TABLE INGRESO ADD CONSTRAINT RefLOTE12 
    FOREIGN KEY (IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO)
    REFERENCES LOTE(IDLOTE, IDCARGAMENTO, FECHAINGRESOINVENTARIO)
;

ALTER TABLE INGRESO ADD CONSTRAINT RefPRODUCTO13 
    FOREIGN KEY (IDPRODUCTO)
    REFERENCES PRODUCTO(IDPRODUCTO)
;

ALTER TABLE INGRESO ADD CONSTRAINT RefOFERTA29 
    FOREIGN KEY (IDOFERTA)
    REFERENCES OFERTA(IDOFERTA)
;


-- 
-- TABLE: LOTE 
--

ALTER TABLE LOTE ADD CONSTRAINT RefCARGAMENTO7 
    FOREIGN KEY (IDCARGAMENTO, FECHAINGRESOINVENTARIO)
    REFERENCES CARGAMENTO(IDCARGAMENTO, FECHAINGRESOINVENTARIO)
;


-- 
-- TABLE: OFERTA 
--

ALTER TABLE OFERTA ADD CONSTRAINT RefTIPOUNIDAD42 
    FOREIGN KEY (IDTIPOUNIDAD)
    REFERENCES TIPOUNIDAD(IDTIPOUNIDAD)
;

ALTER TABLE OFERTA ADD CONSTRAINT RefTIPOOFERTA41 
    FOREIGN KEY (IDTIPOOFERTA)
    REFERENCES TIPOOFERTA(IDTIPOOFERTA)
;


-- 
-- TABLE: OFERTACOTIZACION 
--

ALTER TABLE OFERTACOTIZACION ADD CONSTRAINT RefCOTIZACION19 
    FOREIGN KEY (IDCOTIZACION, FECHACOTIZACION, IDESTADO)
    REFERENCES COTIZACION(IDCOTIZACION, FECHACOTIZACION, IDESTADO)
;

ALTER TABLE OFERTACOTIZACION ADD CONSTRAINT RefOFERTA20 
    FOREIGN KEY (IDOFERTA)
    REFERENCES OFERTA(IDOFERTA)
;


-- 
-- TABLE: PERSONA 
--

ALTER TABLE PERSONA ADD CONSTRAINT RefTIPOPERSONA50 
    FOREIGN KEY (IDTIPOPERSONA)
    REFERENCES TIPOPERSONA(IDTIPOPERSONA)
;


-- 
-- TABLE: PRODUCTO 
--

ALTER TABLE PRODUCTO ADD CONSTRAINT RefCATEGORIA34 
    FOREIGN KEY (IDCATEGORIA)
    REFERENCES CATEGORIA(IDCATEGORIA)
;


-- 
-- TABLE: TARJETA 
--

ALTER TABLE TARJETA ADD CONSTRAINT RefPERSONA45 
    FOREIGN KEY (IDPERSONA)
    REFERENCES PERSONA(IDPERSONA)
;

ALTER TABLE TARJETA ADD CONSTRAINT RefTIPOTARJETA46 
    FOREIGN KEY (IDTIPOTARJETA)
    REFERENCES TIPOTARJETA(IDTIPOTARJETA)
;


-- 
-- TABLE: VENTA 
--

ALTER TABLE VENTA ADD CONSTRAINT RefTIPOPAGO48 
    FOREIGN KEY (IDTIPOPAGO)
    REFERENCES TIPOPAGO(IDTIPOPAGO)
;

ALTER TABLE VENTA ADD CONSTRAINT RefTARJETA56 
    FOREIGN KEY (NOTARJETA, IDPERSONA)
    REFERENCES TARJETA(NOTARJETA, IDPERSONA)
;

ALTER TABLE VENTA ADD CONSTRAINT RefTIPOENTREGA40 
    FOREIGN KEY (IDTIPOENTREGA)
    REFERENCES TIPOENTREGA(IDTIPOENTREGA)
;


