--
-- ER/Studio 7.1 SQL Code Generation
-- Company :      .
-- Project :      Modelo.dm1
-- Author :       gerardo
--
-- Date Created : Sunday, March 10, 2013 20:15:14
-- Target DBMS : MySQL 5.x
--

DROP TABLE AREAPROFESIONAL
;
DROP TABLE ATRIBUTOMATERIAL
;
DROP TABLE CARRERA
;
DROP TABLE CARRERA_AREAPROFESIONAL
;
DROP TABLE CARRERA_POSTGRADO
;
DROP TABLE CLASIFMATERIAL
;
DROP TABLE CURSO
;
DROP TABLE CURSO_MATERIAL
;
DROP TABLE CURSOAPROBADO
;
DROP TABLE ESCUELA
;
DROP TABLE INFOMATERIAL
;
DROP TABLE MATERIALAPOYO
;
DROP TABLE POSTGRADO
;
DROP TABLE REQUISITO
;
DROP TABLE USUARIO
;
-- 
-- TABLE: AREAPROFESIONAL 
--

CREATE TABLE AREAPROFESIONAL(
    IDAREA    DECIMAL(10, 0)    NOT NULL,
    NOMBRE    VARCHAR(75)
)ENGINE=MYISAM
;



-- 
-- TABLE: ATRIBUTOMATERIAL 
--

CREATE TABLE ATRIBUTOMATERIAL(
    IDATRIBUTO    DECIMAL(5, 0)    NOT NULL,
    NOMBRE        VARCHAR(50)
)ENGINE=MYISAM
;



-- 
-- TABLE: CARRERA 
--

CREATE TABLE CARRERA(
    CODCARRERA     DECIMAL(5, 0)    NOT NULL,
    NOMBRE         VARCHAR(50),
    DESCRIPCION    VARCHAR(1000),
    PENSUM         VARCHAR(200),
    IDESCUELA      DECIMAL(2, 0)    NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: CARRERA_AREAPROFESIONAL 
--

CREATE TABLE CARRERA_AREAPROFESIONAL(
    IDAREA        DECIMAL(10, 0)    NOT NULL,
    CODCARRERA    DECIMAL(5, 0)     NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: CARRERA_POSTGRADO 
--

CREATE TABLE CARRERA_POSTGRADO(
    IDPOSTGRADO    DECIMAL(10, 0)    NOT NULL,
    CODCARRERA     DECIMAL(5, 0)     NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: CLASIFMATERIAL 
--

CREATE TABLE CLASIFMATERIAL(
    IDCLASIF    DECIMAL(3, 0)    NOT NULL,
    NOMBRE      VARCHAR(50)
)ENGINE=MYISAM
;



-- 
-- TABLE: CURSO 
--

CREATE TABLE CURSO(
    IDCURSO        DECIMAL(5, 0)    NOT NULL,
    NOMBRE         VARCHAR(50),
    CREDITOS       DECIMAL(2, 0),
    DESCRIPCION    VARCHAR(200)
)ENGINE=MYISAM
;



-- 
-- TABLE: CURSO_MATERIAL 
--

CREATE TABLE CURSO_MATERIAL(
    IDCURSO       DECIMAL(5, 0)     NOT NULL,
    IDMATERIAL    DECIMAL(10, 0)    NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: CURSOAPROBADO 
--

CREATE TABLE CURSOAPROBADO(
    IDCURSO    DECIMAL(5, 0)     NOT NULL,
    CARNET     VARCHAR(300)    NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: ESCUELA 
--

CREATE TABLE ESCUELA(
    IDESCUELA    DECIMAL(2, 0)    NOT NULL,
    NOMBRE       VARCHAR(50),
    UBICACION    VARCHAR(100)
)ENGINE=MYISAM
;



-- 
-- TABLE: INFOMATERIAL 
--

CREATE TABLE INFOMATERIAL(
    IDATRIBUTO    DECIMAL(5, 0)     NOT NULL,
    IDMATERIAL    DECIMAL(10, 0)    NOT NULL,
    VALOR         VARCHAR(200)      NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: MATERIALAPOYO 
--

CREATE TABLE MATERIALAPOYO(
    IDMATERIAL    DECIMAL(10, 0)    NOT NULL,
    IDCLASIF      DECIMAL(3, 0)     NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: POSTGRADO 
--

CREATE TABLE POSTGRADO(
    IDPOSTGRADO    DECIMAL(10, 0)    NOT NULL,
    NOMBRE         VARCHAR(75)
)ENGINE=MYISAM
;



-- 
-- TABLE: REQUISITO 
--

CREATE TABLE REQUISITO(
    PRE     DECIMAL(5, 0)    NOT NULL,
    POST    DECIMAL(5, 0)    NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    CARNET         VARCHAR(300)    NOT NULL,
    NOMBRE         VARCHAR(100),
    CONTRASENIA    VARCHAR(15),
    CORREO         VARCHAR(100)
)ENGINE=MYISAM
;



-- 
-- TABLE: AREAPROFESIONAL 
--

ALTER TABLE AREAPROFESIONAL ADD 
    PRIMARY KEY (IDAREA)
;

-- 
-- TABLE: ATRIBUTOMATERIAL 
--

ALTER TABLE ATRIBUTOMATERIAL ADD 
    PRIMARY KEY (IDATRIBUTO)
;

-- 
-- TABLE: CARRERA 
--

ALTER TABLE CARRERA ADD 
    PRIMARY KEY (CODCARRERA)
;

-- 
-- TABLE: CARRERA_AREAPROFESIONAL 
--

ALTER TABLE CARRERA_AREAPROFESIONAL ADD 
    PRIMARY KEY (IDAREA, CODCARRERA)
;

-- 
-- TABLE: CARRERA_POSTGRADO 
--

ALTER TABLE CARRERA_POSTGRADO ADD 
    PRIMARY KEY (IDPOSTGRADO, CODCARRERA)
;

-- 
-- TABLE: CLASIFMATERIAL 
--

ALTER TABLE CLASIFMATERIAL ADD 
    PRIMARY KEY (IDCLASIF)
;

-- 
-- TABLE: CURSO 
--

ALTER TABLE CURSO ADD 
    PRIMARY KEY (IDCURSO)
;

-- 
-- TABLE: CURSO_MATERIAL 
--

ALTER TABLE CURSO_MATERIAL ADD 
    PRIMARY KEY (IDCURSO, IDMATERIAL)
;

-- 
-- TABLE: CURSOAPROBADO 
--

ALTER TABLE CURSOAPROBADO ADD 
    PRIMARY KEY (IDCURSO, CARNET)
;

-- 
-- TABLE: ESCUELA 
--

ALTER TABLE ESCUELA ADD 
    PRIMARY KEY (IDESCUELA)
;

-- 
-- TABLE: INFOMATERIAL 
--

ALTER TABLE INFOMATERIAL ADD 
    PRIMARY KEY (IDATRIBUTO, IDMATERIAL)
;

-- 
-- TABLE: MATERIALAPOYO 
--

ALTER TABLE MATERIALAPOYO ADD 
    PRIMARY KEY (IDMATERIAL)
;

-- 
-- TABLE: POSTGRADO 
--

ALTER TABLE POSTGRADO ADD 
    PRIMARY KEY (IDPOSTGRADO)
;

-- 
-- TABLE: REQUISITO 
--

ALTER TABLE REQUISITO ADD 
    PRIMARY KEY (PRE, POST)
;

-- 
-- TABLE: USUARIO 
--

ALTER TABLE USUARIO ADD 
    PRIMARY KEY (CARNET)
;

-- 
-- TABLE: CARRERA 
--

ALTER TABLE CARRERA ADD CONSTRAINT RefESCUELA30 
    FOREIGN KEY (IDESCUELA)
    REFERENCES ESCUELA(IDESCUELA)
;


-- 
-- TABLE: CARRERA_AREAPROFESIONAL 
--

ALTER TABLE CARRERA_AREAPROFESIONAL ADD CONSTRAINT RefCARRERA4 
    FOREIGN KEY (CODCARRERA)
    REFERENCES CARRERA(CODCARRERA)
;

ALTER TABLE CARRERA_AREAPROFESIONAL ADD CONSTRAINT RefAREAPROFESIONAL5 
    FOREIGN KEY (IDAREA)
    REFERENCES AREAPROFESIONAL(IDAREA)
;


-- 
-- TABLE: CARRERA_POSTGRADO 
--

ALTER TABLE CARRERA_POSTGRADO ADD CONSTRAINT RefPOSTGRADO2 
    FOREIGN KEY (IDPOSTGRADO)
    REFERENCES POSTGRADO(IDPOSTGRADO)
;

ALTER TABLE CARRERA_POSTGRADO ADD CONSTRAINT RefCARRERA3 
    FOREIGN KEY (CODCARRERA)
    REFERENCES CARRERA(CODCARRERA)
;


-- 
-- TABLE: CURSO_MATERIAL 
--

ALTER TABLE CURSO_MATERIAL ADD CONSTRAINT RefCURSO22 
    FOREIGN KEY (IDCURSO)
    REFERENCES CURSO(IDCURSO)
;

ALTER TABLE CURSO_MATERIAL ADD CONSTRAINT RefMATERIALAPOYO29 
    FOREIGN KEY (IDMATERIAL)
    REFERENCES MATERIALAPOYO(IDMATERIAL)
;


-- 
-- TABLE: CURSOAPROBADO 
--

ALTER TABLE CURSOAPROBADO ADD CONSTRAINT RefUSUARIO25 
    FOREIGN KEY (CARNET)
    REFERENCES USUARIO(CARNET)
;

ALTER TABLE CURSOAPROBADO ADD CONSTRAINT RefCURSO26 
    FOREIGN KEY (IDCURSO)
    REFERENCES CURSO(IDCURSO)
;


-- 
-- TABLE: INFOMATERIAL 
--

ALTER TABLE INFOMATERIAL ADD CONSTRAINT RefATRIBUTOMATERIAL20 
    FOREIGN KEY (IDATRIBUTO)
    REFERENCES ATRIBUTOMATERIAL(IDATRIBUTO)
;

ALTER TABLE INFOMATERIAL ADD CONSTRAINT RefMATERIALAPOYO28 
    FOREIGN KEY (IDMATERIAL)
    REFERENCES MATERIALAPOYO(IDMATERIAL)
;


-- 
-- TABLE: MATERIALAPOYO 
--

ALTER TABLE MATERIALAPOYO ADD CONSTRAINT RefCLASIFMATERIAL27 
    FOREIGN KEY (IDCLASIF)
    REFERENCES CLASIFMATERIAL(IDCLASIF)
;


-- 
-- TABLE: REQUISITO 
--

ALTER TABLE REQUISITO ADD CONSTRAINT RefCURSO8 
    FOREIGN KEY (POST)
    REFERENCES CURSO(IDCURSO)
;

ALTER TABLE REQUISITO ADD CONSTRAINT RefCURSO10 
    FOREIGN KEY (PRE)
    REFERENCES CURSO(IDCURSO)
;


