/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 26/04/2010, 09:14:25 PM
 */

package proy2;

import java.io.File;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
/**
 *
 * @author elzher
 */
public class Menu extends javax.swing.JFrame {

    Abc abc=new Abc();
    String user="usuario",pass="1234567";
    /** Creates new form Menu */
    public Menu() {
        initComponents();
    }

    public void inicio(String user,String pass){
        this.user=user;
        this.pass=pass;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Importar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar tablas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reportes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("ruta de archivos:");

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("carpeta scripts");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("ver scripts");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4))))
                        .addGap(66, 66, 66)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Runtime.getRuntime().exec("iceweasel http://localhost/serverp2/menu.php");
        }catch(Exception e){}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ruta=jTextField1.getText();
        Vector dato1=new Vector();
        Vector dato2=new Vector();
        Vector dato3=new Vector();
        Lector lec=new Lector();
        lec.getData(ruta, dato1, dato2, dato3);
        Conexion con=new Conexion();
        con.abrir(user,pass);
        int f1=dato1.size();
        int f2=dato2.size();
        int f3=dato3.size();
        abc.oScript();
        for(int i=0;i<f2;i++){
            String[] tmp=(String[])dato2.elementAt(i);
            ResultSet rsArea=con.executeQ("select idCliente from cliente where nombre like '"+tmp[0]+"'");
            abc.log("archivo 2: select idCliente from cliente where nombre like '"+tmp[0]+"'");
            try{
                if(rsArea.next())
                    abc.log("repetido, archivo 2: Ya existe el cliente "+tmp[0]);
                else{
                    String s="insert into cliente (nombre,direccion,sector,contacto,puesto,email,admin,tecnico) values ('"+tmp[0]+"','"+tmp[1]+"','"+tmp[2]+"','"+tmp[3]+"','"+tmp[4]+"','"+tmp[5]+"','"+tmp[6].toUpperCase()+"','"+tmp[7].toUpperCase()+"')";
                    con.execute(s);
                    abc.wScript(s, "dato2");
                    abc.log("insercion, archivo 2: "+s);
                }
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 2: "+e.toString());
            }
        }

        for(int i=0;i<f3;i++){
            String[] tmp=(String[])dato3.elementAt(i);
            ResultSet rsCli=con.executeQ("select idCliente from cliente where nombre like '"+tmp[0]+"'");
            abc.log("select idCliente from cliente where nombre like '"+tmp[0]+"'");
            try{
                if(rsCli.next()){
                    String s="insert into licencia (cliente_idCliente,tipo,cantUsuarios,producto,sistOperativo,inicio,fin) values ("+rsCli.getString("idCliente")+",'"+tmp[1]+"',"+tmp[2]+",'"+tmp[3]+"','"+tmp[4]+"','"+tmp[5]+"','"+tmp[6]+"')";
                    con.execute(s);
                    abc.log("insercion, archivo 3: "+s);
                    abc.wScript(s, "dato3");
                }else
                    abc.log("repetido, archivo 3: No existe el cliente "+tmp[0]);
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 3: "+e.toString());
            }

            ResultSet rsArea=con.executeQ("select idArea from area where nombre like '"+tmp[9]+"'");
            abc.log("select idArea from area where nombre like '"+tmp[9]+"'");
            try{
                if(!rsArea.next()){
                    String s="insert into area (nombre) values ('"+tmp[9]+"')";
                    con.execute(s);
                    abc.log("insercion, archivo 3: "+s);
                    abc.wScript(s, "dato3");
                }
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 3: "+e.toString());
            }

            rsArea=con.executeQ("select idArea from area where nombre like '"+tmp[9]+"'");
            abc.log("select idArea from area where nombre like '"+tmp[9]+"'");
            ResultSet rsProd=con.executeQ("select idProducto from producto where nombre like '"+tmp[3]+"'");
            abc.log("select idProducto from producto where nombre like '"+tmp[3]+"'");
            try{
                rsArea.next();//la encuentra seguro, la acaba de insertar
                if(!rsProd.next()){
                    String s="insert into producto (nombre,area_idArea) values ('"+tmp[3]+"',"+rsArea.getString("idArea")+")";
                    con.execute(s);
                    abc.log("insercion, archivo 3: "+s);
                    abc.wScript(s, "dato3");
                }
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 3: "+e.toString());
            }

            rsCli=con.executeQ("select idCliente from cliente where nombre like '"+tmp[0]+"'");
            abc.log("select idCliente from cliente where nombre like '"+tmp[0]+"'");
            rsProd=con.executeQ("select idProducto,area_idArea from producto where nombre like '"+tmp[3]+"'");
            abc.log("select idProducto,area_idArea from producto where nombre like '"+tmp[3]+"'");
            ResultSet rsLic=con.executeQ("select idLicencia from licencia");
            abc.log("select idLicencia from licencia");
            try{
                if(!rsCli.next()){
                    abc.log("repetido, archivo 3: No existe el cliente "+tmp[0]);
                }
                else{
                    int idLic=0;
                    while(rsLic.next())
                        idLic++;
                    rsProd.next();//siempre lo encuentra, lo acaba de insertar
                    String s="insert into venta (cliente_idCliente,unidades,producto_idProducto,sistOperativo,inicio,fin,licencia_idLicencia,area_idArea) values ("+rsCli.getString("idCliente")+","+tmp[2]+","+rsProd.getString("idProducto")+",'"+tmp[4]+"','"+tmp[5]+"','"+tmp[6]+"',"+idLic+","+rsProd.getString("area_idArea")+")";
                    con.execute(s);
                    abc.log("insercion, archivo 3: "+s);
                    abc.wScript(s, "dato3");
                }
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 3: "+e.toString());
            }
        }

        for(int i=0;i<f1;i++){
            String[] tmp=(String[])dato1.elementAt(i);
            ResultSet rsArea=con.executeQ("select idArea from area where nombre like '"+tmp[6]+"'");
            abc.log("select idArea from area where nombre like '"+tmp[6]+"'");
            try{
                if(!rsArea.next()){
                    abc.log("repetido, archivo 1: No existe el area "+tmp[6]);
                }
                else{
                    ResultSet rsCon=con.executeQ("select idConsultor from consultor where nombres like '"+tmp[10]+"'");
                    abc.log("select idConsultor from consultor where nombres like '"+tmp[10]+"'");
                    if(!rsCon.next()){
                        String s="insert into consultor (nombres,email,area_idArea) values ('"+tmp[10]+"','"+tmp[11]+"',"+rsArea.getString("idArea")+")";
                        con.execute(s);
                        abc.log("insercion, archivo 1: "+s);
                        abc.wScript(s, "dato1");
                    }
                }
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 1: "+e.toString());
            }

            ResultSet rsCon=con.executeQ("select area_idArea,idConsultor from consultor where nombres like '"+tmp[10]+"'");
            abc.log("select area_idArea,idConsultor from consultor where nombres like '"+tmp[10]+"'");
            ResultSet rsProd=con.executeQ("select idProducto from producto where nombre like '"+tmp[5]+"'");
            abc.log("select idProducto from producto where nombre like '"+tmp[5]+"'");
            ResultSet rsCli=con.executeQ("select idCliente from cliente where nombre like '"+tmp[1]+"'");
            abc.log("select idCliente from cliente where nombre like '"+tmp[1]+"'");
            try{
                rsCon.next();
                if(!(rsCli.next()))
                    abc.log("repetido, archivo 1: No existe el cliente "+tmp[1]);
                else{
                    if(!rsProd.next()){
                        String s="insert into producto (nombre,area_idArea) values ('"+tmp[5]+"',"+tmp[6]+")";
                        con.execute(s);
                        abc.log(s);
                        abc.wScript(s, "dato1");
                    }
                    ResultSet rsCaso=con.executeQ("select idCaso from caso");
                    abc.log("select idCaso from caso");
                    if(!rsCaso.next()){
                        String s="insert into caso (idCaso,cliente_idCliente,contacto,producto_idProducto,versionSO,inicio,actualizado,consultor_idConsultor,descripcion,estado,severidad,detalle,area_idArea) values ("+tmp[0]+","+rsCli.getString("idCliente")+",'"+tmp[4]+"',"+rsProd.getString("idProducto")+",'"+tmp[7]+"','"+tmp[8]+"','"+tmp[9]+"',"+rsCon.getString("idConsultor")+",'"+tmp[13]+"','"+tmp[14]+"','"+tmp[15]+"','"+tmp[16]+"',"+rsCon.getString("area_idArea")+")";
                        con.execute(s);
                        abc.log("insercion, archivo 1: "+s);
                        abc.wScript(s, "dato1");
                    }
                    else{
                        //con.execute("update caso (idCaso,cliente_idCliente,contacto,producto_idProducto,versionSO,inicio,actualizado,consultor_idConsultor,descripcion,estado,severidad,detalle,area_idArea) values ("+tmp[0]+","+rsCli.getString("idCliente")+",'"+tmp[4]+"',"+rsProd.getString("idProducto")+",'"+tmp[7]+"','"+tmp[8]+"','"+tmp[9]+"',"+rsCon.getString("idConsultor")+",'"+tmp[13]+"','"+tmp[14]+"','"+tmp[15]+"','"+tmp[16]+"',"+rsCon.getString("area_idArea")+")");
                        abc.log("repetido, archivo 1: Ya existe el caso "+tmp[0]);
                    }
                }
                con.cerrar();
                con.abrir(user,pass);
            }catch(Exception e){
                abc.log("excepcion, archivo 1: "+e.toString());
            }
        }
        con.cerrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        menuTabla i=new menuTabla();
        i.inicio(user,pass);
        i.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abc.cLog();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            Runtime.getRuntime().exec("nautilus /home/elzher");
        }catch(Exception e){}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            File f1=new File("/home/elzher/dato1.sql");
            File f2=new File("/home/elzher/dato2.sql");
            File f3=new File("/home/elzher/dato3.sql");
            if(!(f1.exists() && f2.exists() && f3.exists()))
                JOptionPane.showMessageDialog(this, "No se han creado aun");
            else{
                Visor v=new Visor();
                v.setVisible(true);
            }
        }catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
