package Usuarios;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 01 02:47:21 CST 2008
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import javax.swing.*;
import java.util.*;

/** CUP v0.10k generated parser.
  * @version Thu May 01 02:47:21 CST 2008
  */
public class miParserUsuario extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public miParserUsuario() {super();}

  /** Constructor which sets the default scanner. */
  public miParserUsuario(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\004\000\002\002\004\000\002\003\004\000\002\003" +
    "\003\000\002\004\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\013\000\004\007\004\001\002\000\004\004\011\001" +
    "\002\000\004\002\010\001\002\000\006\002\uffff\007\004" +
    "\001\002\000\004\002\000\001\002\000\004\002\001\001" +
    "\002\000\004\007\012\001\002\000\004\004\013\001\002" +
    "\000\004\006\014\001\002\000\004\005\015\001\002\000" +
    "\006\002\ufffe\007\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\013\000\006\003\004\004\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\003\006\004\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$miParserUsuario$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$miParserUsuario$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$miParserUsuario$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public static void main(String args[]) throws Exception{
		new miParserUsuario(new miScannerUsuario(new FileInputStream(args[0]))).parse();
		
	}

	public void syntax_error(Symbol s){
		TokenValue tok=(TokenValue)s.value;
		System.out.println("Error sintactico. Simbolo: "+tok.getLexema());
		//JOptionPane.showMessageDialog(new JFrame(),"Error sintactico. Simbolo: "+tok.getLexema(),"Error sintactico",JOptionPane.ERROR_MESSAGE);
	}

	public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
		TokenValue tok=(TokenValue)s.value;
		System.out.println("Error sin recuperacion. Simbolo: "+tok.getLexema());
		//JOptionPane.showMessageDialog(new JFrame(),"Error sin recuperacion. Simbolo: "+tok.getLexema(),"Error sin recuperacion",JOptionPane.ERROR_MESSAGE);
	}



}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$miParserUsuario$actions {


public Vector Vusuario=new Vector();
public Vector Vclave=new Vector();
public Vector Vestado=new Vector();

  private final miParserUsuario parser;

  /** Constructor */
  CUP$miParserUsuario$actions(miParserUsuario parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$miParserUsuario$do_action(
    int                        CUP$miParserUsuario$act_num,
    java_cup.runtime.lr_parser CUP$miParserUsuario$parser,
    java.util.Stack            CUP$miParserUsuario$stack,
    int                        CUP$miParserUsuario$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$miParserUsuario$result;

      /* select the action based on the action number */
      switch (CUP$miParserUsuario$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expresion ::= ALFANUMERICO COMA ALFANUMERICO COMA ESTADO PCOMA 
            {
              Object RESULT = null;
		int usrleft = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-5)).left;
		int usrright = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-5)).right;
		TokenValue usr = (TokenValue)((java_cup.runtime.Symbol) CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-5)).value;
		int passleft = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-3)).left;
		int passright = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-3)).right;
		TokenValue pass = (TokenValue)((java_cup.runtime.Symbol) CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-3)).value;
		int sttleft = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).left;
		int sttright = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).right;
		TokenValue stt = (TokenValue)((java_cup.runtime.Symbol) CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).value;
		
Vusuario.addElement(usr.getLexema());
Vclave.addElement(pass.getLexema());
Vestado.addElement(stt.getLexema());

              CUP$miParserUsuario$result = new java_cup.runtime.Symbol(2/*expresion*/, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-5)).left, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-0)).right, RESULT);
            }
          return CUP$miParserUsuario$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= expresion 
            {
              Object RESULT = null;
		
              CUP$miParserUsuario$result = new java_cup.runtime.Symbol(1/*inicio*/, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-0)).left, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-0)).right, RESULT);
            }
          return CUP$miParserUsuario$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= expresion inicio 
            {
              Object RESULT = null;
		
              CUP$miParserUsuario$result = new java_cup.runtime.Symbol(1/*inicio*/, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).left, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-0)).right, RESULT);
            }
          return CUP$miParserUsuario$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).value;
		RESULT = start_val;
              CUP$miParserUsuario$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-1)).left, ((java_cup.runtime.Symbol)CUP$miParserUsuario$stack.elementAt(CUP$miParserUsuario$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$miParserUsuario$parser.done_parsing();
          return CUP$miParserUsuario$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

